### ISSUE TITLE
Partial success with adding personas

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/use-case-library-build#1]
I have a question about…i think…python object names?

I did some poking at the use case library build repo, and made some edits on [this branch](https://github.com/nih-cfde/use-case-library-build/tree/addpersonas) to try to add personas. I’ve gotten it to the point where it does:

- actually render a website!
- show my persona in the complete list of contents
- have a spot for persona in the use case

but, even though I think I’ve told it to, it does not:
- have persona in the website header as an option
- make the “this persona is in these use cases” info in the persona file
- actually list the persona in the use case file

I’ve poked it a bunch, and i think the problem is something about the concept of ‘persona’ not being included in the library object list? Because that’s the list that the website header is generating tabs from.
And that this problem might be cause by the fact that i’m not sure how to call things from the library objects correctly. From looking at the other templates, the use case object is obj.use_cases but the library_objects.py doesn’t seem to specify that, so I’m not sure how i would know that without having read the templates. and since persona didn’t exist before, I don’t know whether it’s obj.persona or obj.personas or something else

**Comment by ctb** [comment]
ref https://github.com/nih-cfde/use-case-library-build/pull/2

**Comment by ctb** [comment]
I _think_  aece1c791a11 fixes this, or at least some of it - pls check!

**Comment by ACharbonneau** [comment]
it does fix some of it! lemme see if i can conjure up the rest
