### ISSUE TITLE
Update contributing docs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/use-case-library-build#10]
I've already imported the contributing docs and issue and pr templates from the original use case library, so they just need to be edited to match. 

all pieces of a use case now go into one folder instead of their own folders, and the linking is all automatic. the user needs to fill in the appropriate yaml headers. One thing to note is that *as of right now* the user has to specify requirements both in the use case AND in the task. Eventually I'll fix this so it's *only* in task, but for right now users have to do both places and ensure they match manually

https://github.com/nih-cfde/use-case-library-build/blob/latest/templates/CONTRIBUTING.md

**Comment by marisalim** [comment]
to do list:
- [x] update help desk link
- [x] update repo links
- [x] update PR steps - only change files in library/ (changing files in other directories breaks website). 
- [x] make separate use case docs templates (in main repo directory, does not need to be in gitignore)
- [x] update file name and format instructions
- [x] update PR template check list - take out preview/bot steps for now

**Comment by marisalim** [comment]
have summarized this in the contrib doc -

> the `scripts` take things from `library` and impose them on the appropriate `templates` and then uses `stylesheets` to make them into a website
> changing anything except the contents of `library` unless you are deliberately trying to code in new functionality, will break the everything
