### ISSUE TITLE
Add doneness tagging

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/use-case-library-build#20]
Currently, 'doneness' of a requirement or use case is shown by amanda adding the unicode for a green checkbox in the title of the object.

This is a dumb hack.

Ideally, what I want is to have a yaml header key called "completed" that accepts a "month year" date, and only displays it when that key is filled.

This should be relatively easy to add to the templates, but i'm not sure if I need to do anything fancy in the python script so it doesn't break if the key is blank (where blank would mean `-completed:` as opposed to `-completed: May 2020`)

**Comment by ctb** [comment]
closed by #12
