### ISSUE TITLE
edit use case building code error msg

### ISSUE THREAD

**Issue by marisalim** [nih-cfde/use-case-library-build#34]
For this error message, can we edit the wording:

current:
```
ERROR: use case has disjoint requirements with its tasks' requirements for uc-0001! Requirements are: r-00037, r-00002
```

would like something like this:
```
ERROR: use case has disjoint requirements with its tasks' requirements for uc-0001! add these requirements to uc-0001: r-00037, r-00002
```

**Comment by ACharbonneau** [comment]
That change suggests the error checking is smarter than it is. The error is that you have listed different requirements across the two places, and tells you which requirements don't match. It does not imply which set of requirements (if either) is the *correct* set of requirements, and it can't possibly know that. We need the user to check for the correct requirements, and either add them to one, subtract them from the other, or subtract them from both.

**Comment by marisalim** [comment]
oh i see. hm, maybe `requirements to check:` instead of `requirements are:`?

**Comment by ACharbonneau** [comment]
That would be fine. We are accepting PRs :)
