### ISSUE TITLE
Need to get this into the official cfde domain

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/use-case-library-build#35]
I need instructions and a webaddress to direct to. 

@victor73

**Comment by victor73** [comment]
After some discussion, will be using **use-cases.nih-cfde.org**.

**Comment by ACharbonneau** [comment]
also made 
- docs.nih-cfde.org
- training.nih-cfde.org
 for the technical documentation and training site respectively.

**Comment by s-canchi** [comment]
Here are the [instructions about updating the gh pages to a custom domain](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site)

This requires admin privileges on this repo to modify changes.

**Comment by marisalim** [comment]
the new domain https://use-cases.nih-cfde.org/ was made and link works!
