### ISSUE TITLE
The other use cases that need to be added

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/use-case-library-build#39]
They're all nested here:

https://github.com/nih-cfde/planning-docs/issues/73  --> look at zenhub view!

**Comment by marisalim** [comment]
This is my interpretation of what needs to be added vs. already exists in the UCL from nih-cfde/planning-docs#73. Can @s-canchi and/or @abhijna help me double-check these?

> The goal of Epic 2 is to enable an authorized DCC user to do their own Data Submission, be able to look at that Review Catalog (as was made possible by Epic 1), and to approve Review Catalog for inclusion in the Release Catalog.
 

> There are a number of user stories included in this Epic 

**This is in uc-0004:**
>    - A data administrator installs and configures the CFDE Submission Tool so he can ingest new/updated data packages.

**This is in uc-0004:**
>    - A data administrator uses the CFDE Submission Tool to import a new data package.

**This is in uc-0009:**
>    - A data administrator or data custodian views a display showing the team’s activity including a list of Review Catalogs 
made by team members and relevant diagnostics for each ingest: errors, warnings, summaries.

**This is in uc-0004 but only for data admin. Add data custodian to its persona list?:**
>    - A data administrator or data custodian approves a Review Catalog for use by CFDE.

**This uc needs to be added. We also need a CFDE CC team member persona:**
>    - A CFDE CC team member creates a new version of the CFDE Release Catalog containing the latest approved data package from each DCC team.

**This requirement (?) needs to be added (nothing on UCL currently mentions a "Data Review page":**
> We also know that we need to fix some of the auth/groups connections that we started in Epic 1 to actually make the user experience work. These are in sub-epic:
>    An authenticated portal user can see the Data Review page(s) relevant to their organization(s)

> Dependencies (should be completed in Epic 1):

**This is implied by r-00026, a requirement of uc-0004:**
>    A data custodian authorizes members of her team to use the CFDE Submission Tool and delegates team management and curation roles to individual team members.

**This needs to be added - uc or requirement?:**
>    A data administrator or data custodian views a preview of their Review Catalog for her DCC. The interface includes two sections. The first section the Review Catalog in Chaise. The second section is an administrative summary (a “dashboard”) that allows data integrity and sanity checks. (E.e., "I know i submitted data describing 1,876 mouse subjects, please confirm.")

> Not sure yet if they're in scope for Epic 2:

**This is in uc-0009, but not with CFDE CC persona - sounds like this needs to be a new uc:**
>    A CFDE CC team member views a display showing the activity of the Submission System, including a list of recent Submissions by each DCC team and relevant diagnostics for each Review Catalog: errors, warnings, summaries.

**This is in uc-0008, but not with CFDE CC persona - sounds like this needs to be a new uc:**
>    A CFDE CC team member views a preview of the CFDE portal’s Release Catalog using the Review Catalogs that were approved by each DCC team and either approves or rejects each Review Catalog.

**Comment by s-canchi** [comment]
> This requirement (?) needs to be added (nothing on UCL currently mentions a "Data Review page":

 Isn't this the same as viewing the summary statistics page mentioned in uc-0008 ?

> This is implied by r-00026, a requirement of uc-0004:

This requirement does not mention anything about delegation though. Should that be explicitly a requirement ?

**Comment by marisalim** [comment]
[uc-0004: Submit a Review Catalog](https://github.com/nih-cfde/use-case-library-build/blob/latest/library/uc-0004-create-a-data-release.md) involves the same tasks that would be used for ["Data administrator: installs and configures the CFDE Submission Tools so he can submit new/updated data packages"](https://github.com/nih-cfde/planning-docs/issues/60) & ["Data administrator: uses the CFDE Submission Tool to make a Data Submission"](https://github.com/nih-cfde/planning-docs/issues/59). 

@ACharbonneau Are there differences I'm missing? Should these be kept as separate use cases, or should I update uc-0004? I know uc-0004 was added a while ago and was an earlier version of some of these epic 2 use cases. There are some new tasks that could be added to uc-0004 (e.g., "Follow a minimal example/tutorial for building a metadata manifest", consulting documentation...)

**Comment by marisalim** [comment]
not ready to PR yet, working on https://github.com/nih-cfde/use-case-library-build/tree/marisa-epic2-ucs

**Comment by marisalim** [comment]
Please let me know if this interpretation needs tweaking - for the epic 2 ucs:
- I added ["Data administrator: installs and configures the CFDE Submission Tools so he can submit new/updated data packages"](https://github.com/nih-cfde/planning-docs/issues/60) & ["Data administrator: uses the CFDE Submission Tool to make a Data Submission"](https://github.com/nih-cfde/planning-docs/issues/59) to [uc-0004: Submit a Review Catalog](https://github.com/nih-cfde/use-case-library-build/blob/latest/library/uc-0004-create-a-data-release.md)
- uc-0009 = ["Data administrator: or data custodian views a display showing the team’s activity"](https://github.com/nih-cfde/planning-docs/issues/58)
- uc-0010 = ["Data administrator: approves a Review Catalog for use by CFDE"](https://github.com/nih-cfde/planning-docs/issues/71)
- uc-0011 = ["CFDE CC team member: creates a new version of the CFDE public catalog"](https://github.com/nih-cfde/planning-docs/issues/72)

I added some new tasks and requirements, including a placeholder task (t-9999) and requirement (r-99999). adding these placeholders to new use cases with tasks/requirements not yet defined means the snakemake code will validate.
