### ISSUE TITLE
Incomplete SSL verification

### ISSUE THREAD

**Issue by s-canchi** [nih-cfde/use-case-library-build#43]
The new web domain of the [use cases website ](http://use-cases.nih-cfde.org) shows `Not Secure` in the website url. This issue persists in Safari, Chrome and Firefox.

- [x] A descriptive title
- [x] The behavior you expect to see and the actual behavior observed, including any error messages
- [x] Steps to reproduce the behavior 
- [x] What browser you are using

@ctb @luizirber

**Comment by luizirber** [comment]
https://use-cases.nih-cfde.org/ works, so the certificates are correct. Do you want to make it HTTPS-only? In this case you need to [enforce HTTPS](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site) in the github pages settings of the repo

**Comment by ctb** [comment]
Thanks @s-canchi for finding this, and @luizirber for figuring it out - fixed!
