### ISSUE TITLE
Release Plan- alpha version

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/use-case-library-build#8]
the things I most want and care about are a release tagging system and release notes. I will worry about all the rest of the release plan concept at a much later date

note for @s-canchi : snakemake deploy must be run in order to update the rendered site from the github repo. We should probably think about how to put that in github actions. we might also want to use conda environments in that step, in order to pin the software versions being used

**Comment by s-canchi** [comment]
The release plan along with automation for release notes have been merged. Additional improvement that could be added is separation of the PR types based on labels which can tie back to the different issue templates in place for the repo. Check out the draft of the release notes under `Releases` tab on the main repo page.

**Comment by s-canchi** [comment]
The goals of the original issue have been met. Will open a new issue when time comes to update or revamp the release plan with more details.
